### ISSUE TITLE
When exporting information in the UI, it should select all rows and not those only visible

### ISSUE THREAD

**Issue by chargio** [project-koku/koku-ui#1137]
**Describe the bug**
When exporting the data in the details page, when you select all rows, it should select all data from all accounts, and not only those in the interface. For instance, if you have 1927 results in the header, you should be able to see all data in the export, not only those 10 or 20 rows.

**To Reproduce**

**Expected behavior**
All rows should be selected and a message stating that the full amount of rows has been selected.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dlabrecq** [comment]
That's not how the table works. Row selection only functions on the visible rows. We would need some other mechanism to select all accounts.

**Comment by dlabrecq** [comment]
That's not how the PatternFly table works. Row selection only functions on the visible rows. We would need some other mechanism to select all possible accounts. 

Note that we currently display table selections in the export modal. With paginated data, we have yet to fetch that information; thus, we don't have that information. This wouldn't scale well because, there could be hundreds or thousands of accounts that we must display in the export modal.

**Comment by chargio** [comment]
Is it possible to schedule a task in the backend and make it work through
there?
The current behaviour does not work if the customer is trying to download
the information to work with it, they would need to repeat for each 10-20
rows, stick the information together, and then process it.

Kind regards,
Sergio

Sergio Ocón-Cárdenas

Product Manager, Cost Management

Red Hat <https://www.redhat.com/>

sergio.ocon@redhat.com
M: +34-692058130
<https://www.redhat.com/>

**Comment by dlabrecq** [comment]
Will need to discuss with @adberglund if scheduling tasks is possible. However, I feel that how to represent all data in the UI is more a design issue

**Comment by dlabrecq** [comment]
Created Jira epic https://issues.redhat.com/browse/COST-57
