### ISSUE TITLE
View all tags on details pages for an account without tags shows empty screen

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#1142]
**Describe the bug**
View all tags on details pages for an account without tags shows empty screen

**To Reproduce**
1. Add AWS/Azure provider without any tags
2. Go to 'Cloud details'
3. Click on kebab 'View all tags'
4. See black pop up

**Expected behavior**
If there are no tags we should either disable the 'view all tags' button or have an empty state screen explaining that there are no associated tags on that account.

**Screenshots**
![Screenshot from 2019-12-10 13-39-25.png](https://images.zenhubusercontent.com/5b9a6718443d4b342eb0177e/777605b4-d12f-4486-8581-6b32ce8bbe61)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Firefox
 - Version 70

**Additional context**
Testing against CI Beta

**Comment by dlabrecq** [comment]
This is by design, since we lazily request tag data only when a row is expanded. In order to disable the "View all tags" option, the UI must pre-fetch tags for each table row (e.g., representing each account). For a table with 10 rows, that would be 10 extra requests, which may not be necessary if the user never chooses that option.

That said, I've created an issue with koku https://github.com/project-koku/koku/issues/1534. If the API can be combined to provide the UI with more information, perhaps we can revisit this
