### ISSUE TITLE
Azure historical view charts have no unit vaules in mouse overs

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#1143]
**Describe the bug**
Azure historical view charts have no unit vaules in mouse overs

**To Reproduce**
1. Add/Ingest Azure provider
2. Go to 'Cloud details'
3. Click on 'historical view'
4. Mouse over compute/storage charts
5. Notice there is no unit value in mouse overs

**Expected behavior**
We should show the unit with the value

**Screenshots**
![Screenshot from 2019-12-10 13-59-08.png](https://images.zenhubusercontent.com/5b9a6718443d4b342eb0177e/54a7ca0a-d742-4c0c-8346-0d66dd62bdc6)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser: Firefox
 - Version: 70

**Additional context**
Found testing against CI beta

**Comment by dlabrecq** [comment]
The Azure API currently does not provide units

**Comment by dlabrecq** [comment]
The Azure API currently does not provide correct units. For example, the usage units are "Instance Type Placeholder", while count units are "instances"

<img width="575" alt="Screen Shot 2019-12-10 at 10 19 05 PM" src="https://user-images.githubusercontent.com/17481322/70588602-42a1c400-1b9b-11ea-9dd1-2385745212ff.png">

Note this is due to https://github.com/project-koku/koku/issues/1360
