### ISSUE TITLE
Use REST cache-control headers in API

### ISSUE THREAD

**Issue by boaz0** [project-koku/koku-ui#1167]
## User Story
As a developer, I want to use cache-control headers so that the UI won't render unnecessarily.

https://github.com/project-koku/koku/commit/cbe7de9c84f22f51a65c7cabdf2301f633b2529d

## Impacts
UI

## Acceptance Criteria

- [ ] Use cache control headers to make sure the current state in Redux is the latest

**Comment by dlabrecq** [comment]
Can you please elaborate how the UI should use this (e.g., for all requests, cost model only, etc.)? 

Currently, the UI caches most reports for 30 min client-side. (We don't generate a new request until the current report expires.) However, there are requests that we don't want to cache such as providers.

See: https://github.com/project-koku/koku-ui/blob/master/src/store/azureReports/azureReportsActions.ts#L32

Perhaps we can discuss whether we should continue to follow that approach or introduce something different for all? 

I didn't implement the current approach myself, but it's been used in our code since Aug 2018. If we can demonstrate cache-control headers work as expected for our requests, I'm fine with using that instead providing we can be consistent.

**Comment by boaz0** [comment]
Hi @dlabrecq thank you for looking at it.
You're right, this ticket is vague and needs more details.

1. The back-end engineers set what API endpoints the UI should cache.
2. It's easy to know what request are cached by checking the Cache-control header in the response headers.
3. Using the cache-control we can avoid sending a new request to get the new request and instead send a new request when the date mentioned in the cache-control expires.
4. This can be used instead of the current way we cache the data but just for the API endpoints that have this support.

I hope these three points help understand the ticket better.

**Comment by dlabrecq** [comment]
If the back-end controls the cache, it's possible we can just remove our client-side code and rely on the the browser to fetch when requests expire.

**Comment by boaz0** [comment]
Probably yes.
Lets just see what parts we're caching and decide to drop or not the client-side caching there.
What do you think?

**Comment by dlabrecq** [comment]
Decided we will not to port this issue to Jira.

**Comment by dlabrecq** [comment]
Decided we will not to port this issue to Jira.
