### ISSUE TITLE
Show cost instead of infrastructure_cost

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#1206]
For Ocp cloud infrastructure, it appears that we should display `cost` instead of `infrastructure_cost`. 

On the details page, we're currently showing the `delta` (i.e., month over month change); however, that is in sync with `cost`. Thus, showing the cost delta with `infrastructure_cost` seems incorrect.

"My impression is that we should just always use the cost value being reported by the API. In the case of the openshift /instractructure APIs it is the infrastructure cost + any applicable markup." -- @adberglund 

@chargio Did you specifically want to omit showing markup here? Should we file an issue to add support for `infrastructure_cost` deltas? Or, just show cost?

FYI, the infrastructures API below shows `cost` in sync with `delta`, not `infrastructure_cost`.

`/api/cost-management/v1/reports/openshift/infrastructures/all/costs/?delta=cost`

<img width="534" alt="Screen Shot 2020-01-02 at 2 54 04 PM" src="https://user-images.githubusercontent.com/17481322/71690604-301e4300-2d73-11ea-9494-b13b718c061c.png">

**Comment by chargio** [comment]
@dayleparker We had the discussion about this. Do you remember the outcome of our discussions?

**Comment by dlabrecq** [comment]
@chargio @dayleparker We basically need to know if Ocp on cloud infrastructure should include markup or not?

**Comment by dlabrecq** [comment]
"Yes. But it should be possible to see them separated" -- @chargio 

We have a tooltip and popover for "Ocp details", but not for "Ocp on cloud infrastructure". Perhaps, we could add that separately?


Ocp details:
<img width="375" alt="Screen Shot 2020-01-02 at 4 12 34 PM" src="https://user-images.githubusercontent.com/17481322/71693711-28629c80-2d7b-11ea-968b-bffc4a727fbd.png">

Ocp overview:
<img width="484" alt="Screen Shot 2020-01-02 at 4 15 31 PM" src="https://user-images.githubusercontent.com/17481322/71693703-239de880-2d7b-11ea-9c6f-918b6bbb38c6.png">

**Comment by chargio** [comment]
OCP costs are distributed costs, so showing the total cost is ok.
It would be great in the future to show infra costs (both raw costs , markups and node costs, and other costs), but right now total is the most correct amount

**Comment by dayleparker** [comment]
OK, I have been using the discussion in https://github.com/project-koku/koku/issues/1397 to refresh my fuzzy memory... :|

@dlabrecq - just to make sure, are we discussing the page titled "OpenShift cloud infrastructure details" (vs. in #1397 we discussed the details page titled "OpenShift details")?

If yes -
The outcome of the discussion regarding markup I believe was that markup is only applied to raw costs (costs coming from a third party like AWS, Azure, subscription management). I think we don't show those raw costs on this screen so IMHO 'markup' wouldn't need to be shown on this screen. This screen is **only** for showing the OpenShift costs, independent of the cloud infra it's running on... I think.

Does that sound right, @chargio ?

**Comment by adberglund** [comment]
@dayleparker @chargio  

### OpenShift Details
Any and all OpenShift costs. This includes those running on a (cloud) infrastructure provider and OpenShift clusters for which the cost comes from a price list on a cost model.

### OpenShift Cloud Infrastructure Details
Only OpenShift costs from a (cloud or other) infrastructure provider. As it exists today, this is really just a subset of the data from the Cloud Details. Today this page encompasses OpenShift on AWS and OpenShift on Azure, so it's actually just AWS and Azure data. Because markup is shown on the cloud tab/details I think we need it here too. 

We have previous discussed the idea of folding OpenShift on Cloud Infrastructure tab on the dashboard into the cloud tab, where it would just become a filter option. A user might go to the cloud tab and say "I want to see all of my cloud costs." Then they might say "Okay, now just show me the cloud cost required to run my OpenShift clusters" and the data would just filter down, but it's always the same source. Does this make sense?

**Comment by dayleparker** [comment]
Thanks for your explanation, @adberglund. I am always getting confused about which tab is a subset of which (so +1 to the filter option in the future) @dlabrecq please disregard my earlier comment.
