### ISSUE TITLE
UI User can add new cost models and edit them in the interface

### ISSUE THREAD

**Issue by chargio** [project-koku/koku-ui#1338]
**Describe the bug**
A user is capable of following the Ui to create or modify cost models, even if he has no rights to do so.

**To Reproduce**
1. Go to 'Cost models'
2. Click on 'Create new model'
3. Follow the workflow and select a source

**Expected behavior**
The platform shows a "this feature is read only". I was expecting all the buttons to be disabled if the user is read only (no create new cost model, you can see the model but you can't modify, delete or add rates)

**Screenshots**
![image](https://user-images.githubusercontent.com/7500590/75162612-17505f00-571e-11ea-883e-8f6725f91e56.png)

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Browser [Firefor, chrome, safari]
 - Version [latest]

**Additional context**
It looks like the user can edit things he can't

**Comment by boaz0** [comment]
OK - so I couldn't reproduce this anymore on production but I figured out where I can get retrieve this information.

Using chrome insights:

```
return insights.chrome.auth.getUser().then((user) => {
  const isOrgAdmin = user.identity.user.is_org_admin;
  // ... do something with this information ...
})
```

Probably storing this in Redux will be useful in the future.

**Comment by nlcwong** [comment]
Affected actions (in primary buttons & in kebabs options): 
- Create cost model
- Delete cost model
- Add rate
- Delete rate
- Edit markup
- Assign source
- Unassign source

Expected behavior: 
In addition to enable/disable button/links, include a tooltip with following text:
"You do not have permission to create or delete a cost model."
"You do not have permission to add, edit, or remove a rate."
"You do not have permission to assign or unassign a source."

@adberglund @chambridge  Can the UI call the RBAC APIs directly to check to see if the user has permissions for cost model CRUD?  If so, what would that API be for us to check to see if a button/action/link should be enabled/disabled due to permissions?

**Comment by adberglund** [comment]
@boaz0 @nlcwong did you see this https://github.com/RedHatInsights/insights-chrome/blob/master/src/js/entry.js#L125-L127 is that useful here? I don't think knowing if they're an org admin is good enough here.

**Comment by boaz0** [comment]
@adberglund that's what I thought but that returns `true` or `false` and @nlcwong gave me the impression it's more granular than that.

**Comment by boaz0** [comment]
@adberglund @chargio @nlcwong  I did look at https://github.com/RedHatInsights/insights-chrome/blob/master/src/js/entry.js#L125-L127 and I am confused because there are accounts that doesn't contain "cost-managements" in the response from that rbac.

In addition, in the one account that had "cost-management" rbac data, it had all the permissions which didn't shade any light what am I suppose to do or parse the data.

Looking more into the code, I got to this code:
https://github.com/RedHatInsights/javascript-clients/blob/master/packages/rbac/api.ts#L77-L90

Not sure exactly what are the different parts in the permissions string
The resourceDefinitions attribute is empty array in all the account so I have no idea what I am going to do with that.

Is there any contacts from the RBAC team?

**Comment by dchorvat1** [comment]
verified
