### ISSUE TITLE
Get the version or build in the GUI

### ISSUE THREAD

**Issue by vestival** [project-koku/koku-ui#136]
## User Story
As a user I want to know which version or build am I using so I can understand if there's been any change or update, at least in the staging environment

## Impacts
UI

## UI Details
I would expect something like "About" under "Help"

## Acceptance Criteria

- Get the version or build

**Comment by boaz1337** [comment]
@chambridge @nlcwong should we have a design for that or we can use patternfly's about modal: https://www.patternfly.org/pattern-library/communication/about-modal/

**Comment by chambridge** [comment]
I appreciate the request, but as we will soon be integrating with the insights platform we need to know more how the user is/could be presented with this information from that point of view.

While this is something for @nlcwong to dig into (as each app will likely want to be able to show specific for that) I don't see this as a high priority as anything we would do here would be thrown away as we move from a standalone app to an embedded component of insights.

**Comment by chambridge** [comment]
Environment variables are now available with things like commit hash when this PR goes in:
https://github.com/project-koku/koku-ui/pull/156/files#diff-11e9f7f953edc64ba14b0cc350ae7b9dR101

We just need to determine how this can be surfaced in the UI.

@nlcwong Any thoughts on this? How about we just bake it into the bottom right corner of the screen?

![image.png](https://images.zenhubusercontent.com/59651c6861b4ca3b0a740ad4/2e1ac3be-4eca-40c8-adaa-8d3eb62c9493)

**Comment by nlcwong** [comment]
@vestival I just emailed the insights platform team asking them if they have any use cases/requirements of needing to bubble this to the UI and they said not right now.  Knowing that there are no plans for Insights to support an About modal in the UI, I would like to close this issue out as a no-fix as I still do not have any indication that an end-user/external would benefit from this since we are supposedly delivering content in a continuous manner.  Is that OK with you?

**Comment by vestival** [comment]
Yes, please close it

**Comment by nlcwong** [comment]
The platform is handling this issue in the about modal.
