### ISSUE TITLE
Replace PF3 listView with PF4 component

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#207]
Note that this PF4 component is not currently available -- scheduled for 1.0.0-alpha.5 (Oct-Nov 9).
See https://docs.google.com/spreadsheets/d/17aEfvG1DZ0dZmpwacYaCzKv4sog0LuatXCwNizJ7HhE/edit#gid=205680820

## User Story
Replace the PF3 listView component with the PatternFly 4 data list component. This is currently being used in the AWS and OCP detail pages.

## Impacts
UI

## Assumptions
The PatternFly 4 component can achieve similar visualizations.

## UI Details
See http://patternfly-react.surge.sh/patternfly-4

## Acceptance Criteria

The pages achieve similar functionality with the new PF4 component.

**Comment by karelhala** [comment]
I would like to point out that data list to show these data is probably wrong and Table should be used here. Data list are ment as alternative view to cards for instance because they lack certain actions and accessibility.

For instance Data list doesn't have any header to show at the top so no sorting is available as well. When table is shown on small devices it behaves somewhat differently - select boxes and actions are in different place.

So unless you are showing somewhat static data (less than 10 for each user) and we do not expect to filter, sort and paginate over these items consider using Table instead of Data lists.

**Comment by dlabrecq** [comment]
This issue was more a placeholder to replace the PF3 list. I believe we will be more interested in using the table Vs data list in favor of features similar to the PF3 list -- both are available in pF4 now.
