### ISSUE TITLE
Overview page requires multiple refresh attempts before provider data is displayed

### ISSUE THREAD

**Issue by LandoCalrizzian** [project-koku/koku-ui#250]
**Describe the bug**
When accessing the overview page after first login, the "Add Provider" page is displayed indicating there is no provider data even though one or more providers returned by the api. The page requires 2-3 refresh attempts before the provider data is displayed in the UI

**To Reproduce**
1. Login to Insights and access Cost Management
2. Overview page only displays text for adding a provider because no provider was found
3. Refresh the page 2-3 times to populate the UI w/ provider data

**Expected behavior**
Provider data is queried and displayed when providers are present

**Desktop (please complete the following information):**
 - Browser Chrome 69 and Firefox 62

**Additional context**
Once data is cached in the session there are no issues

**Comment by dlabrecq** [comment]
This is an issue with the Insights platform related to tokens

**Comment by chambridge** [comment]
Insights team has provided a promise that we can wrap our API calls in to make sure we always have a token:
https://docs.google.com/document/d/1xjITNYbp1aw9Xu3lYLQppKQl-Rtj6_BaThwy1Zkazm4/edit#heading=h.8aucqk7x2oqb

We need to implement this in our code.

**Comment by chargio** [comment]
+1

This is still happening @dlabrecq I can show you if you need to see it

**Comment by vestival** [comment]
it happens the same to me

**Comment by chargio** [comment]
![image](https://user-images.githubusercontent.com/7500590/49285287-55b58a80-f497-11e8-860e-c77f8d8b13a6.png)

**Comment by dlabrecq** [comment]
I've opened a new Insights issue. 
https://github.com/RedHatInsights/insights-chrome/issues/76

**Comment by lcouzens** [comment]
This is not completely blocking UI automation but is holding it up a lot, is there anything we can do to resolve it sooner? I will raise priority to high.

**Comment by chambridge** [comment]
I messaged into frontend channel on slack to try and get some eyes on the issue.

**Comment by boaz1337** [comment]
As mentioned in https://github.com/RedHatInsights/insights-chrome/issues/76
I believe the cause of this is the timeouts between the frontend and the backend.
We can solve this in two ways:

 1) Stretch the timeout for 7 seconds. This is good for short-term as this might fix the problem for 90% but what happens if the latency will be higher. In addition, this is not really user friendly to wait longer.

 2) Try to fetch the data in 3 tries and if it keeps failing display an error message with the option to try again. For example, if in the first try the request failed due to timeout a new request will be sent. If the error is not because of timeout or this was the 3rd try - the error will be displayed (f.e. "Failed fetching providers data from sever due to ...") with an action button to try again and fetch the data. This option looks good to me because it is more robust and more user friendly.

WDYT?

**Comment by dlabrecq** [comment]
Probably a combination of both. I'd like to see us add the retries, in addition to extending the timeout to address the latency problem. I don't know if the fetch button is necessary with the retries, but will defer to @nlcwong?

**Comment by chambridge** [comment]
At the last November 16 Insights demo meeting the Platform team demo showed off notifications. Might be a useful mechanism to display timeout errors after we hit the retry limit.
