### ISSUE TITLE
Undescriptive class names and ids

### ISSUE THREAD

**Issue by quarckster** [project-koku/koku-ui#332]
```html
<div class="css-70qvj9">
    <h1 class="pf-c-title pf-m-4xl css-10s0eea">$2.98</h1>
    <div class="css-0">
        <div class="css-z0b0om">Total Cost</div>
        <div class="css-7h5mdo">Since December 1</div>
    </div>
</div>
```
Such class and id names are not very helpful when you want to write ui automated test. It would be nice to have more descriptive id and class names in elements. Beforementioned example would better look like this:
```html
<div class="cost-block">
    <h1 class="pf-c-title pf-m-4xl" id="cost">$2.98</h1>
    <div class="additional-info">
        <div class="total-cost">Total Cost</div>
        <div class="since-data">Since December 1</div>
    </div>
</div>

**Comment by dlabrecq** [comment]
The css-z0b0om class name is generated dynamically by the Emotion library. We've inherited the CSS style functionality from PatternFly and that is not likely to change.

Using CSS classes isn't good for automated tests because we cannot guarantee the selector names won't change. Ideally, test IDs should be used for automation testing. If there are hooks you need us to add, please open another issue to let us know what you need.
