### ISSUE TITLE
EPIC: Dashboard

### ISSUE THREAD

**Issue by dmiller9911** [project-koku/koku-ui#34]
Epic for everything on the dashboard page for the crawl phase.

**Comment by nlcwong** [comment]
Latest mocks (high fidelity), see first 3 slides for the visual look/feel of the HCCM dashboard.
Missing from the high fidelity (add additional AWS account button & Top 5 breakdowns (instead of top 3), but a summary bar).

https://redhat.invisionapp.com/share/BJN9KGLTUD8

Following is the annotated dashboard wireframes to call out data, data format, and interaction attributes of a UI component: https://redhat.invisionapp.com/share/CDN40VZKB28
