### ISSUE TITLE
Units are shown as gb in AWS storage

### ISSUE THREAD

**Issue by chargio** [project-koku/koku-ui#349]
**Describe the bug**
The costs are shown in graphics and lists as gb, they should be GB or GiB (depending on the real unit) and it should be shown always as the same unit.

**To Reproduce**
Go to the details page for OCP

**Expected behavior**
Units should be coherent with the input. For money, $ or any other currency configured.

![imagen](https://user-images.githubusercontent.com/7500590/49790624-00973580-fd2f-11e8-9fb9-1eadbcca4897.png)

**Comment by chargio** [comment]
I was navigating through Insights and I was redirected to Beta

**Comment by boaz1337** [comment]
I am afraid that's not going to be fixed in #348 
#348 fixes the problem in the summary report details: 
Right now it shows "582 hrs Hrs" while it's supposed to be "582 Hrs".

Regarding the units - this information is received from the backend. Some data came without units so that's why you don't see it in the tooltip. :arrow_backward:  @chambridge correct me if I'm wrong.

**Comment by chargio** [comment]
I've seen the same behaviour both in AWS and OCP. The picture if from AWS.

If "gb" is received from the backend, and sometimes it is missing, that is a separate bug. Units should be consistent and always used. 243 is nothing, 243 GB is what it should be shown (or 243 GiB if that is the case, they should not be confused)
