### ISSUE TITLE
Order of legend should be different for OCP

### ISSUE THREAD

**Issue by chargio** [project-koku/koku-ui#351]
**Describe the bug**
the order looks wrong

**Expected behavior**
legend should be aligned with graphics (green and blue descriptions under the green and blue graphics)

**Screenshots**
![imagen](https://user-images.githubusercontent.com/7500590/49791005-ced29e80-fd2f-11e8-9896-997baa4c416b.png)

**Comment by chambridge** [comment]
@chargio please do not assign people to issue. If you want them to see it just mention them in a comment.

**Comment by boaz1337** [comment]
I am not sure I understand what's the problem.
Can you give more details what is wrong or what is expected? Maybe adding a screenshot with the expected behaviour.

Thanks @chargio

**Comment by chargio** [comment]
![imagen](https://user-images.githubusercontent.com/7500590/49813155-217b7d00-fd67-11e8-8eeb-06934ec5fd29.png)

As you can see there is a misalignment between the graphic and the legend

**Comment by chargio** [comment]
I was expecting blue and green to be under blue and green if the are on the left side

**Comment by boaz1337** [comment]
I see. Thanks @chargio 
@nlcwong and @dlabrecq - is that true for area charts too? Do items in the legend should be under each other?

**Comment by chambridge** [comment]
@chargio There isn’t any left or right; there is just a gap in data because we started capturing it in the middle of November. This is a single chart covering the beginning of the month to the end. 

This doesn’t seem to be a bug to me, we can certainly get more user feedback. But for now it appears as designed (IMHO).

**Comment by chargio** [comment]
@nlcwong What do you think?
Should we also add the zeros?

**Comment by dlabrecq** [comment]
The returned API report simply has missing data for those dates. Missing or empty data, results in a zero value for those particular days. Natalie and I spoke about this and the chart is showing what is expected for this edge-case.

If you look at the value in the tooltip, the data we have for the month of November starts on the 12th. Similarly, the data for the month of December begins on the 1st, but only runs to December 11th. The gap you see is the missing dates (days 11-12) between the current and previous months. 

As data is accumulated for the month of December, that gap will close. Similarly, if we had a full months worth of data in November, there wouldn't be a gap.

For the month of January, I expect this will look more like the AWS dashboard. That is, because we will have a full months worth of data to show for December

**Comment by dlabrecq** [comment]
FYI, the colors will be adjusted when the new chart color pallet is added to patternfly-react. These are not final colors, just colors (place holders) that are currently available in patternfly.

**Comment by dlabrecq** [comment]
We could reorder the AWS legend labels, so the previous month is first, as shown below? 

![2](https://user-images.githubusercontent.com/17481322/49822933-71007f80-fd4c-11e8-9c3a-9e06280c0a00.png)

That won't effect the alignment of how data is shown in the chart, tho. If any alignment is perceived, that would just be a coincidence. The data would no longer align with the legend toward the mid/end of December.

**Comment by lcouzens** [comment]
I like the idea of changing the legend ordering. :+1: I also thought maybe we could align the legend date with the imported data? I mean in reality its again a bit of an edge case, as it should only happen the first time you add a provider/import data. (also assuming the imported data does not start at the month beginning) Just a thought probably more of a pain to implement than its worth.

And just because we all like screen shots this is what the graphs should really look like currently with the whole month data :+1: 

![screenshot from 2018-12-11 20-08-39](https://user-images.githubusercontent.com/18352403/49827558-8217b380-fd81-11e8-95db-e2897d44729a.png)

**Comment by dlabrecq** [comment]
Yes, the charts would look more like that, given appropriate data. 

We originally showed a legend for Nov 12-30, but @nlcwong asked to show that as Nov 1-30 because it's the date range we are trying to cover for the month. It's not a big deal to change the date, one way or the other, but will defer to Natalie.

**Comment by lcouzens** [comment]
I just noticed in my screenshot the dates are showing Nov 1-29, looking at the API I am missing data for the 30th but as you said the date range should still be 1-30 right? I guess the legend always starts at 1 but ends where the data stops hence current month stays inline with the current date. Is previous month doing something similar? Perhaps this needs to be changed so the previous month end date is always the last date of that month?

**Comment by chargio** [comment]
It was an edge case but it was really confusing... Looking at the latest graphics it makes more sense.  I always wonder about the difference between no data and data that is zero.

Reordering the legend seems nice, I expect the legend to be in a more natural order (left to right, up to down) , or if it was possible even be part of the graphic itself.

Dates should be Nov 1-30 for the past month, as we already have all the data. In the future when we have forecasting the forecast should show up to the end of the month (with a different representation, like a dotted line).

**Comment by dlabrecq** [comment]
We only adjust the starting date, not the ending date. Thus, the legend for the current month shows Dec 1-11. We could adjust the legend for the previous month, but would also have to account for different ending dates, leap years, etc.
