### ISSUE TITLE
Add source modal is referencing upstream docs

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#421]
**Describe the bug**
When using the add source modal it has a link to documentation which refers back to upstream docs. We should have it replaced by downstream docs; an article on access.redhat.com might suffice for MVP

**To Reproduce**
1. Navigate to insights/platform/cost-management/
2. Click on Add a Source
3. Click on link to Koku documentation

**Expected behavior**
This should probably change from 'Koku documentation' to 'documentation' and should link to some downstream docs/redhat article.

**Screenshots**
![screenshot from 2019-01-21 14-26-46](https://user-images.githubusercontent.com/18352403/51480474-0bf76b00-1d89-11e9-8799-ea7d5d3768f1.png)

**Additional context**
(I assume this is because we have been waiting for an official docs person) This is more so we have it tracked.

**Comment by dlabrecq** [comment]
This modal is in the process of being completely replaced by #201. There will be a modal wizard flow per Natalie's new mocks. Thus, I will close this issue in favor of that work.

**Comment by dlabrecq** [comment]
This modal is in the process of being completely replaced by #201. There will be a modal wizard flow per Natalie's new mocks.

**Comment by boaz0** [comment]
@lcouzens @dlabrecq didn't find the downstream docs. Any help will be appreciated.

**Comment by dlabrecq** [comment]
I don't understand myself. The new modal design will also have links to docs.

**Comment by jkrocil** [comment]
@dlabrecq Is the new modal going to have links to **downstream** docs? Because that's the issue here. We **can't** link to upstream koku docs. Thanks

**Comment by dlabrecq** [comment]
I'd like to better understand why linking to Koku docs is an issue? @jkrocil can you please clarify?

We now have a doc writer assigned to the Cost Management project, but don't know of any plans to create "downstream" docs at this time. I assume

Perhaps @chargio / @nlcwong can also chime in here?

**Comment by dayleparker** [comment]
@dlabrecq Hi! I'm the docs writer on Cost Management, and on my to-do list is working through how/where we'll publish the downstream docs. I have a meeting scheduled with our content strategist to figure out the logistics and will keep everyone updated when I know the downstream link.

We need to link to downstream docs from the RH-branded Cost Management UI for support reasons -- whatever is published on the RH Customer Portal is supported for customers (by Red Hat support) and therefore tested by RH QE. The upstream version of the product can link to the Koku docs though. We're currently discussing something like what we do for ManageIQ/CloudForms. 

@jkrocil please correct me if I'm understanding this wrong...

**Comment by chargio** [comment]
@dlabrecq I don't know if the policy is always the same, but in many open source projects, the product has different documentation. Mainly because the logo is different, and the names too, and also because some functionality can be upstream but not downstream, or the opposite (i.e. integration to third party proprietary products)

It is also a matter of testing and format. In many cases, that only means using some variable instead of a name or a link so it can be updated appropriately.

**Comment by jkrocil** [comment]
@dlabrecq @chargio @dayleparker Ok, sounds good to me! It's completely understandable that we want to keep upstream links in upstream and have productized docs in downstream. So I believe the issue here really is that we are reporting a downstream issue to an upstream GH. :wink: 

Do we have a JIRA project to report this to yet? If so, I think it's reasonable to close this one.

Thanks
