### ISSUE TITLE
New add source modal failure message non discriptive 

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#542]
**Describe the bug**
New add source modal failure message non discriptive 

**To Reproduce**
1. Go to Overview
2. Click on 'Add a Source'
3. Fill out modal with details from a already added provider

**Expected behavior**
We should give a clear indication of the error.
'Source has already be added to account'

**Screenshots**
![screenshot from 2019-02-27 11-19-10](https://user-images.githubusercontent.com/18352403/53486817-b85ff780-3a81-11e9-9d88-00c9b88400a2.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Chrome
 - Version 66

**Additional context**
Testing against CI insightsbeta

**Comment by boaz0** [comment]
I am not sure 100% but from my understanding if the descriptive failure message stored in `data.Error` of the response. Since it wasn't there, the error message (`Request failed with status code 400`) was printed.

Here is the [code lines](https://github.com/project-koku/koku-ui/blob/master/src/pages/onboardingModal/final/loader.tsx#L64-L65):
```js
  if (err.response && err.response.data && err.response.data.Error) {
    errorMessage = err.response.data.Error;
  }
```

**Comment by lcouzens** [comment]
Not sure, but here's the json response in the api.
```
{
    "errors": [
        {
            "detail": "A Provider already exists with that Authentication and Billing Source",
            "source": "Error",
            "status": 400
        }
    ]
}
```

**Comment by boaz0** [comment]
That's great. I will use that! Thanks a bunch
