### ISSUE TITLE
Enable price list in details kebab while grouped by project, cluster, & node

### ISSUE THREAD

**Issue by boaz0** [project-koku/koku-ui#739]
## User Story
As user, I expect to see the price list option in the details kebab, while grouped by cluster. However, it would be a nice addition if the price list were also available when grouped by project and node. Since the cluster name is available, it should be possible to enable the price list option in the details kebab.

## Impacts
Ex. UI, Docs

## Role
User

## Assumptions
- Details kebab is available via https://github.com/project-koku/koku-ui/issues/627
- Price list option will be disabled while grouped by "Tags"

## Acceptance Criteria

- [x] Each item in the table will continue to show a Kebab menu
- [x] Kebab menu will always have a "View price list" option
- [x] View price list is disabled when grouped by Tags

**Comment by dlabrecq** [comment]
During our last conversation, it was my impression that we needed the cluster name, which grouped by tags does not provide. Thus, we suggested to disable the price list while grouped by tag.

While reviewing the price list, I noticed the code does not depend on the cluster associated with the group by. I now see that we're obtaining UUIDs from a request to the providers API.

That said, it would not matter if the user grouped by cluster, tag, etc. I believe the kebab could show the price list enabled, regardless of what group by has been applied.

@nlcwong Do we really want to disable when grouped by tag?

**Comment by dlabrecq** [comment]
After speaking with @nlcwong, I believe we should only enable when group by cluster. Disable when group by is anything else.

I'm thinking that we also need to pass the cluster to the price list modal. I believe the intention of having a kebab in each table row is to show the price lists associated with individual clusters.

The demo works because we only have one provider, but there will be others.

**Comment by nlcwong** [comment]
Thank you @dlabrecq for pointing this out.  What I also want to point out is that for the OpenShift details, its possible that a selected cluster might not have a price list attached to it (because it is an OpenShift cluster whose infrastructure is on AWS), would it be technical possible that we have the ability to know if there is a price list associated with a cluster so that when they click on the kebab, it would disable the view price list link if the cluster did not have a price list associated with it?  Actually, is there a flag of some sort to know if that cluster is on AWS?

**Comment by dlabrecq** [comment]
Currently, the rates API request is generated only when the user selects the price list option in the kebab. If there is no price list for the associated cluster, a "No rates were found" message is displayed in the modal. 

Note that the rates API request is intentionally lazily loaded for better page loading performance. Similar to expanding a row, we want to avoid making extra requests that may go unused.

We could change this so that the request is made when the user loads the details page. Thus, the price list option in the kebab can be disabled when there's nothing associated with an individual cluster. 

That said, would we be making an extra request for something that is rarely used? We're currently making up to 6 API data requests when the details page is rendered. Don't feel strongly against adding another, but something to consider.

**Comment by dlabrecq** [comment]
After speaking with @nlcwong, it sounds like users may want an empty state to explain why there is no price list (and how to create one) for a given cluster? Currently, when the price list option is disabled, users have no explanation as to why.

In the Ocp details page, we also have clusters on AWS. However, the clusters on AWS are not known to the UI. If the APIs could provide that information, we could disable the price list option (or hide it), when a cluster is on AWS. Until then, I suggest we continue to lazily load, but show an empty state in the price list modal.

**Comment by boaz0** [comment]
Sounds reasonable but I will open a new issue for that as it will be easy for me to manage.

**Comment by boaz0** [comment]
Opened ticket #797 to address empty state in the modal.
