### ISSUE TITLE
Hitting 'Enter' key after typing in to add source modal loads overview page

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku-ui#813]
**Describe the bug**
Hitting 'Enter' key after typing in to add source modal loads overview page

**To Reproduce**
1. Go to 'Add sources' page
2. Click on 'Add source'
3. Type a source name
4. Hit enter key

**Expected behavior**
Either enter should do nothing or default to 'Continue' button

**Screenshots**
![Screenshot from 2019-04-29 13-36-45](https://user-images.githubusercontent.com/18352403/56896638-2aee5300-6a84-11e9-91bd-2a943a2ecd53.png)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Firefox
 - Version 66

**Additional context**
Testing against PROD

**Comment by boaz0** [comment]
Thanks @lcouzens 
I can reproduce this problem. It happens when the text input is focused.
I am really confused as I didn't specify at any place what to do when clicking enter.
I guess there is a component that catches this enter event and triggers the refreshing.

I will try to figure it out if I have time.
