### ISSUE TITLE
Unexpected spikes in per region compute hours

### ISSUE THREAD

**Issue by chargio** [project-koku/koku-ui#90]
**Describe the bug**
Compute instance hours per region are not looking right

**To Reproduce**
1. Open the interface in Firefox
2. Navigate to the dashboard (by default)
3. Look at compute instance hours
4. Select Tag Top Regions

**Expected behavior**
The graphic should remain the same.

**Screenshots**
![screen shot 2018-08-28 at 10 48 53](https://user-images.githubusercontent.com/7500590/44712128-61686e00-aab0-11e8-81ac-ee253c0e8489.png)
![screen shot 2018-08-28 at 10 48 59](https://user-images.githubusercontent.com/7500590/44712129-62010480-aab0-11e8-8d9b-aa79ed62f1ac.png)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Firefox
 - Version 61.0.2

**Additional context**
The data should be the same grouped by region. You can see spikes in the graphics

**Comment by chambridge** [comment]
The issue with compute instance hours is due to the fact that AWS seems to have “issues” with reporting free tier level instances. Many times the cost and usage report will not contain any units or region data or resource IDs for this level of instances. This is more a bug in the AWS report than against our service. We’ve currently decided this seems less important to try and “fix” on our end as our customers are not likely to be using free tier level systems for the majority of their EC2 usage.
