### ISSUE TITLE
RFE: Sources UI: Add a 'are you sure you want to cancel?' failsafe

### ISSUE THREAD

**Issue by dayleparker** [project-koku/koku-ui#918]
Can we provide a failsafe/extra check when the user hits Cancel? (ie. a popup window like "Are you sure you want to cancel adding this source?") 

It looked like a lot of info to collect while adding an OpenShift source, and could be a real pain for the user to retrieve all these values again if they hadn't noted the details somewhere else, and accidentally hit the Cancel button.

Not sure if we already have this in motion, but here's an idea I had after watching the Bluejeans recording (see the 14/06/19 BJN recording #2 at 1:09:00) for adding an OCP source.

**Comment by boaz0** [comment]
Hi @dayleparker can you send me a link to it through email.
Because I wasn't attended in that meeting (14/06/19) and I don't have the spreadsheet with all the meetings and records.

I am guessing you're not talking about the meeting we had in Mahwah because I looked at Chapter 2 and there was nothing about it.

I guess I will just add a confirmation dialog box before closing the wizard widget. Will that be OK?
Thanks.

**Comment by dayleparker** [comment]
Hi @boaz0 -- just emailed you with a link to the video. Sorry not to provide it earlier! I am not sure of our process but we should get Natalie's OK before going ahead. Thanks for working on this :)

**Comment by nlcwong** [comment]
@boaz0 & @dayleparker by all means, please include a confirmation message asking if the user is really sure that they want to exit the wizard before getting to the end!  This confirmation dialog should also work with the "X" button as well as they both act like that cancel/close action.  I don't think there is a patternfly code yet for a message dialog, but I totally would think it would be in the same style as the confirmation dialogs we have for the delete actions (maybe not as direly worded).  Please let me know if you need an exact mock for it.

**Comment by boaz0** [comment]
No, it's OK. I can figure this out.
Thanks @nlcwong
