### ISSUE TITLE
Sources > add source modal resumes after cancelling 

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku-ui#942]
**Describe the bug**
After cancelling add source modal after some steps, when we try to add new source and select its type, the modal returns us to the step in which we closed the first modal.

**To Reproduce**
1. Go to sources
2. Click on "Add source", go through the onboarding and cancel at the confirmation
3. Click on "Add source" again, select the provider type
4. See that modal resumed to the confirmation dialog, without filling in any information

**Expected behavior**
Correct modal navigation, selecting provider type shouldn't skip any steps at all.

**Screenshots**
![Screenshot from 2019-08-12 12-02-57](https://user-images.githubusercontent.com/46324552/62858609-0d738b00-bcfb-11e9-8503-9b9a58bc2b4f.png)

**Desktop (please complete the following information):**
 - OS: rhel
 - Browser Chrome 75

**Additional context**
Tested on CI beta/stable

**Comment by boaz0** [comment]
Thanks @dchorvat1 I will look at it now.

**Comment by boaz0** [comment]
OK the problem is simple. The index of the step we are is stored in the component and not in the Redux. Now I thought rendering the first step if `type` is not set will solve that. However, to really solve it I need to set `index` to 0 if type is not set before rendering the wizard.

I will push a fix in the following hours.
